spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
      redis:
        time-to-live: 10m